steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['config', 'set', 'project', 'prodiego3']

# Build the container images
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/prodiego3/miregistry/minode:v1', '-f', 'server/Dockerfile', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/prodiego3/miregistry/minode:v1']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args: [
    "-c",
    "gcloud run deploy react-nodejs-cloudbuilds-server
    --image=europe-west1-docker.pkg.dev/prodiego3/miregistry/minode:v1
    --region=europe-west1
    --platform=managed
    --allow-unauthenticated
    --port=3000
    --update-env-vars DB_URL_ATLAS=$$DB_URL_ATLAS"
  ]

  secretEnv: [
    'DB_URL_ATLAS'
  ]
images:
- 'europe-west1-docker.pkg.dev/prodiego3/miregistry/minode:v1'

availableSecrets:
  secretManager:
    - versionName: projects/277567353585/secrets/secreto2/versions/1
      env: 'DB_URL_ATLAS'