steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['config', 'set', 'project', 'prodiego2']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/prodiego2/repoejergcp/minode/mimagenbuild:1.0', '-f', 'server/Dockerfile', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/prodiego2/repoejergcp/minode/mimagenbuild:1.0']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args: [
    "-c",
    "gcloud run deploy react-nodejs-cloudbuilds-server 
    --image=gcr.io/prodiego2/repoejergcp/minode/mimagenbuild:1.0
    --region=europe-west1 
    --platform=managed 
    --allow-unauthenticated 
    --port=3000 
    --update-env-vars DB_URL_ATLAS=$$DB_URL_ATLASbuild"
  ]

  secretEnv: [
    'DB_URL_ATLASbuild'
  ]
images:
- 'gcr.io/prodiego2/repoejergcp/minode/mimagenbuild:1.0'

availableSecrets:
  secretManager:
    - versionName: projects/89654536036/secrets/secreto2/versions/1
      env: 'DB_URL_ATLASbuild' 